name: 002 Generate Artifact Names
on:
  workflow_call:
    inputs:
      release_tag:
        type: string
        description: Release tag to use for the installer and upgrader
    outputs:
      mysql:
        description: MySQL snapshot name
        value: ${{ jobs.generate-database-artifact-names.outputs.mysql }}
      postgres:
        description: Postgres snapshot name
        value: ${{ jobs.generate-database-artifact-names.outputs.postgres }}
      short_sha:
        description: Short SHA of the commit
        value: ${{ jobs.generate-database-artifact-names.outputs.short_sha }}

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  generate-database-artifact-names:
    name: Generate Artifact Names
    runs-on:
      - self-hosted
      - oracle-linux-8
      - small
    outputs:
      mysql: ${{ steps.output-artifact-names.outputs.mysql }}
      postgres: ${{ steps.output-artifact-names.outputs.postgres }}
      short_sha: ${{ steps.generate-short-sha.outputs.short-sha }}
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: 175452
          private_key: ${{ secrets.CLOUDBOLT_ACTION_HELPER_PEM }}

      - uses: actions/checkout@v4.1.1
        with:
          path: main
          submodules: "recursive"
          token: ${{ steps.generate-token.outputs.token }}

      - name: Read Build Facts
        id: read-build-facts
        working-directory: main
        run: |
          echo "company=$(cat ./COMPANY)" >> $GITHUB_OUTPUT

      - name: Generate Short Sha
        id: generate-short-sha
        working-directory: main
        run: |
          echo "short-sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Output Artifacts
        id: output-artifact-names
        working-directory: main
        run: |
          echo "mysql=mysql_backup_${{ inputs.release_tag }}_${{ steps.generate-short-sha.outputs.short-sha}}.sql" >> $GITHUB_OUTPUT
          echo "postgres=postgres_backup_${{ inputs.release_tag }}_${{ steps.generate-short-sha.outputs.short-sha}}.tar" >> $GITHUB_OUTPUT
