name: 002 Build CloudBolt RPM
# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      release_tag:
        type: string
        description: Release tag to use for the installer and upgrader
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        description: Release tag to use for the installer and upgrader
        required: true

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  build-rpm-el7:
    name: Build EL7 RPM
    uses: ./.github/workflows/build.rpm.el7.yml
    with:
      release_tag: ${{ github.event.inputs.release_tag || 'v2022.4.2' }}
    secrets: inherit
  build-rpm-el8:
    name: Build EL8 RPM
    uses: ./.github/workflows/build.rpm.el8.yml
    with:
      release_tag: ${{ github.event.inputs.release_tag || 'v2022.4.2' }}
    secrets: inherit
  rpm-test:
    name: RPM Test install
    uses: ./.github/workflows/build.rpm.test.yml
    needs:
      - build-rpm-el8
    with:
      release_tag: ${{ github.event.inputs.release_tag || 'v2022.4.2' }}
    secrets: inherit
  build-rpm-update-repo:
    name: Update RPM REPO
    uses: ./.github/workflows/build.rpm.update-repo.yml
    needs:
      - build-rpm-el8
    with:
      release_tag: ${{ github.event.inputs.release_tag || 'v2022.4.2' }}
    secrets: inherit
