name: HUI Smoke Tests
on:
  workflow_call:
    inputs:
      release_tag:
        type: string
        description: Release tag to use for the installer and upgrader
      upgrader_presigned_url:
        type: string
        description: Presigned URL for the upgrader
        required: true

defaults:
  run:
    shell: bash -leo pipefail {0}

permissions: write-all

jobs:
  smoke-test:
    name: Smoke Test
    runs-on:
      - self-hosted
      - ubuntu
      - large
    environment:
      name: Smoke Tests
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: 175452
          private_key: ${{ secrets.CLOUDBOLT_ACTION_HELPER_PEM }}

      - name: Checkout Test-Automation Repo
        uses: actions/checkout@v4.1.1
        with:
          repository: CloudBoltSoftware/test-automation
          ref: develop
          token: ${{ steps.generate-token.outputs.token }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          role-skip-session-tagging: true

      - name: Launch CloudBolt-GA EC2 Instance
        id: launch-ec2-instance
        uses: CloudBoltSoftware/launch-ec2-template-action@v1.3.2
        with:
          launch_template_name: CloudBolt-GA
          aws_region: ${{ vars.AWS_REGION }}

      - name: Upgrade CMP Instance
        uses: CloudBoltSoftware/upgrade-cmp-action@v1.0.4
        with:
          ip-address: ${{ steps.launch-ec2-instance.outputs.ip_address }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-user: ${{ vars.SSH_USER }}
          upgrader-url: ${{ inputs.upgrader_presigned_url }}

      - name: Configure CMP
        uses: CloudBoltSoftware/configure-cmp-action@v1.3.2
        with:
          ip-address: ${{ steps.launch-ec2-instance.outputs.ip_address }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-user: ${{ vars.SSH_USER }}
          ec2-instance-id: ${{ steps.launch-ec2-instance.outputs.instance_id }}
          disable-configurator: true
          license: ${{ secrets.LICENSE }}
          disable-guided-setup: true

      - name: Wait for CMP to be ready
        uses: CloudBoltSoftware/wait-for-cmp-readiness-action@v1.1.0
        with:
          ip: ${{ steps.launch-ec2-instance.outputs.ip_address }}
          protocol: https
          timeout: 300

      - name: Run Playwright HUI Tests
        uses: ./.github/actions/run-pipeline-automation
        id: run-pipline-automation
        with:
          ip-address: ${{ steps.launch-ec2-instance.outputs.ip_address }}
          numprocesses: auto
          dist: load
          additional_options: "-m smoke"
          test_area_name: HUI-Smoke-${{ inputs.release_tag }}

      - name: Generate Token Post Test Run
        id: generate-token-post-run
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: 175452
          private_key: ${{ secrets.CLOUDBOLT_ACTION_HELPER_PEM }}

      - name: Report New Failures to Slack
        id: report-new-failures-to-slack
        uses: ./.github/actions/send-new-test-failures-to-slack
        if: ${{ !cancelled() }}
        with:
          run-id: ${{ github.run_id }}
          repository: ${{ github.repository }}
          download-path: /tmp/pytest-results
          artifact-name: pytest-results
          launch-info-json: launch_info.json
          notify-slack: true
          slack-channel-id: C03BDR2NZT4
          rp-username: cb-cicd
          rp-password: ${{ secrets.RP_PASSWORD }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          github-token: ${{ steps.generate-token-post-run.outputs.token }}

      - name: Set Outputs
        run: |
          echo "| Key | Description | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| ip | IP address of the CloudBolt server used for smoke tests | ${{ steps.launch-ec2-instance.outputs.ip_address }} |" >> $GITHUB_STEP_SUMMARY
          echo "| ec2-instance | EC2 instance ID of the CloudBolt server used for smoke tests | ${{ steps.launch-ec2-instance.outputs.instance_id }} |" >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
