name: Increment PR Tag
on:
  workflow_call:
    outputs:
      release_tag:
        value: ${{ jobs.tag.outputs.release_tag }}
        description: The release tag to use for the pull request analysis
jobs:
  tag:
    name: Increment Tag
    runs-on:
      - self-hosted
      - oracle-linux-8
      - small
    outputs:
      release_tag: ${{ steps.output-new-tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: 175452
          private_key: ${{ secrets.CLOUDBOLT_ACTION_HELPER_PEM }}

      - name: Get latest GA tag
        id: get-latest-ga-tag
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          LATEST_GA_TAG=$(gh api repos/:owner/:repo/releases --jq '.[] | .tag_name | select(contains("-") | not)' --paginate | sort -V | tail -n 1);
          echo "* LATEST_GA_TAG: $LATEST_GA_TAG" >> $GITHUB_STEP_SUMMARY
          echo "latest_ga_tag=$LATEST_GA_TAG" >> $GITHUB_OUTPUT

      - name: Get latest PR tag
        id: get-latest-PR-tag
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          LATEST_PR_TAG=$(gh api repos/:owner/:repo/releases --jq '.[] | .tag_name | select(contains("-PR${{ github.event.number }}"))' --paginate | sort -V | tail -n 1;)
          echo "* LATEST_PR_TAG: $LATEST_PR_TAG" >> $GITHUB_STEP_SUMMARY
          echo "latest_pr_tag=$LATEST_PR_TAG" >> $GITHUB_OUTPUT

      - name: Select base version
        id: select-base-version
        run: |
          BASE_TAG=$(cat <<EOF | sort -V | tail -n 1
          ${{ steps.get-latest-ga-tag.outputs.latest_ga_tag }}
          ${{ steps.get-latest-PR-tag.outputs.latest_pr_tag }}
          EOF
          )
          echo "* BASE_TAG: $BASE_TAG" >> $GITHUB_STEP_SUMMARY
          echo "base_tag=$BASE_TAG" >> $GITHUB_OUTPUT
      
      - name: Create Initial PR
        id: create-initial-PR
        if: ${{ !contains(steps.select-base-version.outputs.base_tag, '-PR') || contains(steps.select-base-version.outputs.base_tag, '-rc') }}
        run: |
          BASE_VERSION=$(echo '${{ steps.select-base-version.outputs.base_tag }}' | awk -F'-' '{print $1}')
          NEW_TAG=$(echo "$BASE_VERSION-PR${{ github.event.number }}.1")
          echo "* NEW_TAG: $NEW_TAG" >> $GITHUB_STEP_SUMMARY
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Increment PR
        id: increment-PR
        if: ${{ contains(steps.select-base-version.outputs.base_tag, '-PR') }}
        run: |
          NEW_TAG=$(echo '${{ steps.select-base-version.outputs.base_tag }}' | awk -F'.' '{print $1"."$2"."$3"."$4+1}')
          echo "* NEW_TAG: $NEW_TAG" >> $GITHUB_STEP_SUMMARY
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Output new tag
        id: output-new-tag
        run: |
          echo "new_tag=${{ steps.create-initial-PR.outputs.new_tag || steps.increment-PR.outputs.new_tag }}" >> $GITHUB_OUTPUT

      - name: Save PR Description to .md
        id: save-pr-description
        env:
          PR_DESCRIPTION: ${{ github.event.pull_request.body }}
        run: |
          echo "Saving PR description to pr-description.md"
          echo "${{ env.PR_DESCRIPTION }}" > pr-description.md

      - name: Create Pre-Release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        id: create-pre-release
        run: >
          gh release create ${{ steps.output-new-tag.outputs.new_tag }}
          --title ${{ steps.output-new-tag.outputs.new_tag }}
          --prerelease
          --target ${{ github.event.pull_request.head.sha }}
          --notes-file pr-description.md
